In [ ]:
# libraries in Python
# NumPy, pandas, matplotlib, seaborn.

In [1]:
import numpy as np

In [ ]:
# creating numpy array

In [2]:
# Single-Dimensional Array

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
# Multi-Dimenional Array

arr = np.array([[1, 2, 3],[4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# initializing with 0

n1 = np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
# initializing with same number

n1 = np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [10]:
n1 = np.full((4,3),5)
n1

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
# initializing within a range

n1 = np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
n1 = np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
# joining numpy array

In [16]:
# vstack()

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
# hstack()

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [18]:
# column_stack()

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [19]:
# numpy intersection(common value) and difference (uncommon value)

In [20]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([40,50,60,70,80,90])

np.intersect1d(arr1,arr2)

array([40, 50, 60])

In [21]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([40,50,60,70,80,90])

np.setdiff1d(arr1,arr2)

array([10, 20, 30])

In [22]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([40,50,60,70,80,90])

np.setdiff1d(arr2,arr1)

array([70, 80, 90])

In [23]:
# numpy array mathematics

In [25]:
#basic addition (addition to each number)

n1 = np.array([10,20,30])
n1 = n1 + 1
print(n1)

[11 21 31]


In [26]:
# basic subtraction

n1 = np.array([10,20,30])
n1 = n1 - 1
print(n1)


[ 9 19 29]


In [27]:
# basic multiplication

n1 = np.array([10,20,30])
n1 = n1 * 2
print(n1)

[20 40 60]


In [28]:
# basic division

n1 = np.array([10,20,30])
n1 = n1 / 2
print(n1)

[ 5. 10. 15.]


In [ ]:
# numpy Math Functions

In [29]:
# Mean

n1 = np.array([10,20,30,40,50,60])
np.mean(n1)


35.0

In [30]:
# Median

n1 = np.array([11,44,5,96,67,85])
np.median(n1)

55.5

In [31]:
# Standard Deviation

n1 = np.array([1,5,3,100,4,48])
np.std(n1)

36.59424666377065

In [3]:
# Python Pandas - data manipulation and data analysis


In [39]:
import pandas as pd

In [6]:
# Pandas Series Object

In [20]:
# create a series from list (index and Series)

data = [10,20,30,40,50]
series = pd.Series(data)
print(series)                 

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [21]:
# changing index

In [22]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [23]:
s1 = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [24]:
# create a series from dictionary

In [25]:
pd.Series({'a':10,'b':20,'c':30,'d':40})


a    10
b    20
c    30
d    40
dtype: int64

In [26]:
# extracting individual elements

In [29]:
# single element/ element from back/ squence of element.

s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s1[9]


10

In [30]:
s1[5]

6

In [33]:
s1[-4:]

6     7
7     8
8     9
9    10
dtype: int64

In [34]:
s1[0:5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [35]:
s1[:3]

0    1
1    2
2    3
dtype: int64

In [36]:
# basic Maths Operation on Series

In [37]:
# adding

s1= pd.Series([1,2,3,4,5,6,7,8,9,10])
s1+1

0     2
1     3
2     4
3     5
4     6
5     7
6     8
7     9
8    10
9    11
dtype: int64

In [38]:
s1= pd.Series([1,2,3,4,5,6,7,8,9,10])
s2= pd.Series([10,20,30,40,50,60,70,80,90,100])

s1+s2

0     11
1     22
2     33
3     44
4     55
5     66
6     77
7     88
8     99
9    110
dtype: int64

In [41]:
# Pandas DataFrames - 2 dimensional data structure
# DataFrame - comprises of rows and columns

In [43]:
# creating DataFrame from list

data = [1,2,3,4,5,]
df = pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [45]:
# creating DataFrame from Dictionary

data = {'Name':['John','Emma','Peter','Ovi'],
        'Age': [25,30,35,28],
        'city': ['New York','London','Paris','Sydney']}

df = pd.DataFrame(data)
print(df)

    Name  Age      city
0   John   25  New York
1   Emma   30    London
2  Peter   35     Paris
3    Ovi   28    Sydney


In [ ]:
# DataFrame in- built function - len(), head(), tail(), describe(),
# shape(), dtypes().

In [50]:
# loc [] - selction of index - name matching

In [52]:
print(df.loc[0:3,('Name','Age')])

    Name  Age
0   John   25
1   Emma   30
2  Peter   35
3    Ovi   28


In [53]:
# iloc []- selection of index - column index also

In [57]:
print(df.iloc[0:3,0:2])

    Name  Age
0   John   25
1   Emma   30
2  Peter   35


In [58]:
# dropping rows/ axis

In [60]:

data = {'Name':['John','Emma','Peter','Ovi'],
        'Age': [25,30,35,28],
        'city': ['New York','London','Paris','Sydney']}

df = pd.DataFrame(data)
print(df)

    Name  Age      city
0   John   25  New York
1   Emma   30    London
2  Peter   35     Paris
3    Ovi   28    Sydney


In [64]:
df.drop([0,3],axis=0)

Name  Age    city
1   Emma   30  London
2  Peter   35   Paris

In [ ]:
# dropping columns

In [69]:

data = {'Name': ['John', 'Emma', 'Peter', 'Olivia'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'London', 'Paris', 'Sydney']}

df = pd.DataFrame(data)

print(df)

     Name  Age      City
0    John   25  New York
1    Emma   30    London
2   Peter   35     Paris
3  Olivia   28    Sydney


In [70]:
df.drop(['City'],axis=1)

Name  Age
0    John   25
1    Emma   30
2   Peter   35
3  Olivia   28

In [72]:
# adding new column to DataFrame.

In [93]:
data = {'Name': ['John', 'Emma', 'Peter', 'Olivia'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'London', 'Paris', 'Sydney']}
df = pd.DataFrame(data)

print(df)

     Name  Age      City
0    John   25  New York
1    Emma   30    London
2   Peter   35     Paris
3  Olivia   28    Sydney


In [94]:
df['Country'] = ['USA', 'UK', 'France', 'Australia']
print(df)

     Name  Age      City    Country
0    John   25  New York        USA
1    Emma   30    London         UK
2   Peter   35     Paris     France
3  Olivia   28    Sydney  Australia


In [75]:
# modifying values in DataFrame

In [95]:
df ['Age'] = [26,31,36,29]
print(df)

     Name  Age      City    Country
0    John   26  New York        USA
1    Emma   31    London         UK
2   Peter   36     Paris     France
3  Olivia   29    Sydney  Australia


In [96]:
df.loc[0, 'City'] = 'Chicago'
print(df)

     Name  Age     City    Country
0    John   26  Chicago        USA
1    Emma   31   London         UK
2   Peter   36    Paris     France
3  Olivia   29   Sydney  Australia


In [97]:
# filtering rows in a DataFrame

In [98]:
filtered_df = df[df['Age']>30]
print(filtered_df)

    Name  Age    City Country
1   Emma   31  London      UK
2  Peter   36   Paris  France


In [99]:
data = {'Name': ['John', 'Emma', 'Peter', 'Ovi'],
        'Age': [25, 30, 35, 28],
        'Height': [170, 165, 180, 175],
        'Weight': [70, 65, 80, 75]}
df = pd.DataFrame(data)
df

Name  Age  Height  Weight
0   John   25     170      70
1   Emma   30     165      65
2  Peter   35     180      80
3    Ovi   28     175      75

In [100]:
df.min()

Name      Emma
Age         25
Height     165
Weight      65
dtype: object

In [101]:
df.max()

Name      Peter
Age          35
Height      180
Weight       80
dtype: object

In [102]:
df

Name  Age  Height  Weight
0   John   25     170      70
1   Emma   30     165      65
2  Peter   35     180      80
3    Ovi   28     175      75

In [103]:
df[['Age', 'Height', 'Weight']]

Age  Height  Weight
0   25     170      70
1   30     165      65
2   35     180      80
3   28     175      75

In [105]:
def half(s):
    return s*0.5

In [106]:
df[['Age', 'Height', 'Weight']].apply(half)

Age  Height  Weight
0  12.5    85.0    35.0
1  15.0    82.5    32.5
2  17.5    90.0    40.0
3  14.0    87.5    37.5

In [107]:
data = {'Name': ['John', 'Emma', 'Peter', 'Olivia', 'John', 'Emma'],
        'Age': [25, 30, 35, 28, 25, 30],
        'City': ['New York', 'London', 'Paris', 'Sydney', 'New York', 'London']}
df = pd.DataFrame(data)
df

Name  Age      City
0    John   25  New York
1    Emma   30    London
2   Peter   35     Paris
3  Olivia   28    Sydney
4    John   25  New York
5    Emma   30    London

In [108]:
print(df['Name'].value_counts())

Name
John      2
Emma      2
Peter     1
Olivia    1
Name: count, dtype: int64


In [109]:
print(df.sort_values(by='Age'))

     Name  Age      City
0    John   25  New York
4    John   25  New York
3  Olivia   28    Sydney
1    Emma   30    London
5    Emma   30    London
2   Peter   35     Paris


In [110]:
print(df.sort_values(by='Name'))

     Name  Age      City
1    Emma   30    London
5    Emma   30    London
0    John   25  New York
4    John   25  New York
3  Olivia   28    Sydney
2   Peter   35     Paris
